// get posts =>
export const SEND_REQUEST_POSTS = 'SEND_REQUEST_POSTS';
export const GET_POST_REQUEST_RESPONSE = 'GET_POST_REQUEST_RESPONSE';
export const GET_POST_REQUEST_ERROR = 'GET_POST_REQUEST_ERROR';

// search posts =>
export const GET_PSOT_SEARCH_RESPONSE = 'GET_PSOT_SEARCH_RESPONSE';
export const GET_POST_SEARCH_ERROR = 'GET_POST_SEARCH_ERROR';

// delete posts =>
export const SEND_REQUEST_DELETE_POSTS = 'SEND_REQUEST_DELETE_POSTS';
export const DELETE_POSTS_RESPONSE = 'DELETE_POSTS_RESPONSE';
export const DELETE_POSTS_ERROR = 'DELETE_POSTS_ERROR';
