// get GALLERY =>
export const SEND_REQUEST_GALLERY = 'SEND_REQUEST_GALLERY';
export const GET_GALLERY_REQUEST_RESPONSE = 'GET_GALLERY_REQUEST_RESPONSE';
export const GET_GALLERY_REQUEST_ERROR = 'GET_GALLERY_REQUEST_ERROR';

// search GALLERY =>
export const GET_GALLERY_SEARCH_RESPONSE = 'GET_GALLERY_SEARCH_RESPONSE';
export const GET_GALLERY_SEARCH_ERROR = 'GET_GALLERY_SEARCH_ERROR';

// delete GALLERY =>
export const SEND_REQUEST_DELETE_GALLERY = 'SEND_REQUEST_DELETE_GALLERY';
export const DELETE_GALLERY_RESPONSE = 'DELETE_GALLERY_RESPONSE';
export const DELETE_GALLERY_ERROR = 'DELETE_GALLERY_ERROR';
