// get COMMENT =>
export const SEND_REQUEST_COMMENT = 'SEND_REQUEST_COMMENT';
export const GET_COMMENT_REQUEST_RESPONSE = 'GET_COMMENT_REQUEST_RESPONSE';
export const GET_COMMENT_REQUEST_ERROR = 'GET_COMMENT_REQUEST_ERROR';

// search COMMENT =>
export const GET_COMMENT_SEARCH_RESPONSE = 'GET_COMMENT_SEARCH_RESPONSE';
export const GET_COMMENT_SEARCH_ERROR = 'GET_COMMENT_SEARCH_ERROR';

// delete COMMENT =>
export const SEND_REQUEST_DELETE_COMMENT = 'SEND_REQUEST_DELETE_COMMENT';
export const DELETE_COMMENT_RESPONSE = 'DELETE_COMMENT_RESPONSE';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';
