// get users =>
export const SEND_REQUEST_USERS = 'SEND_REQUEST_USERS';
export const GET_REQUEST_RESPONSE = 'GET_REQUEST_RESPONSE';
export const GET_REQUEST_ERROR = 'GET_REQUEST_ERROR';

// search users =>
export const GET_SEARCH_RESPONSE = 'GET_SEARCH_RESPONSE';
export const GET_SEARCH_ERROR = 'GET_SEARCH_ERROR';

// delete users =>
export const SEND_REQUEST_DELETE_USERS = 'SEND_REQUEST_DELETE_USERS';
export const DELETE_USERS_RESPONSE = 'DELETE_USERS_RESPONSE';
export const DELETE_USERS_ERROR = 'DELETE_USERS_ERROR';
